### ISSUE TITLE
Time to release it!

### ISSUE THREAD

**Issue by r3nya** [michael-ciniawsky/gulp-postcssrc#1]
Hey!

Do you want to release it on npm? 😉

**Comment by michael-ciniawsky** [comment]
The reason why it's currently unpublished is, that we try to keep the PostCSS ecosystem consistent when possible. Either PostCSS integrates `postcss-load-config` into it's core or gulp-postcss gets an update. Originally this module is more of an PoC, but when there is no progress in the near future, I'm 'forced' to release it anyways, since it's also ducktaping our workflow at work atm :)

**Comment by michael-ciniawsky** [comment]
[gulp-postcss #92](https://github.com/postcss/gulp-postcss/issues/92)

**Comment by r3nya** [comment]
@michael-ciniawsky ah, gotcha. Thanks for your reply! 😉

**Comment by michael-ciniawsky** [comment]
@r3nya finally released in `gulp-postcss` v6.3.0+
