### ISSUE TITLE
'gulp-postcssrc' is not in the npm registry

### ISSUE THREAD

**Issue by jingsam** [michael-ciniawsky/gulp-postcssrc#8]

**Comment by michael-ciniawsky** [comment]
Yeah.. its's PoC,bc original author of gulp-postcss refuses to add `postcss-load-comfig` to gulp-postcss, blabla here blabla there. I promised to leave it unpublished for a while to not 'divide' postcss ecosystem in terms of tooling, but if there is no progress I will/need to release it in tandem with CLI (PoC) , Grunt (PoC), since I'm one of the maintainers of postcss-loader for webpack at least that works 😛 .

**Comment by jingsam** [comment]
That's great! thanks

**Comment by michael-ciniawsky** [comment]
@jingsam finally released in `gulp-postcss` v6.3.0+
